In [5]:
import torch
import numpy as np

In [61]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype = 'float32')

In [62]:
targets = np.array([[56, 70],
                   [81, 101],
                   [119, 133],
                   [22 , 37],
                   [103, 119]], dtype = 'float32')

In [63]:
targets.shape

(5, 2)

In [64]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


#### Initializing/ Defining Weights & Biases

In [65]:
w = torch.randn(2,3, requires_grad = True)
b = torch.randn(2,requires_grad = True)
print(w)
print(b)

tensor([[-1.3682, -0.8082, -0.1005],
        [ 1.7920,  1.0713, -0.5000]], requires_grad=True)
tensor([-1.1030,  0.3866], requires_grad=True)


In [66]:
w.shape, b.shape

(torch.Size([2, 3]), torch.Size([2]))

#### Define the model

In [67]:
def model(x):
    return x @ w.t() + b

#### generate predictions

In [68]:
preds = model(inputs)

#### MSE loss

In [69]:
def mse(t1,t2):
    diff = t1-t2
    return torch.sum(diff*diff)/diff.numel()

### Compute loss

In [70]:
loss = mse(preds, targets)
loss

tensor(45506.1641, grad_fn=<DivBackward0>)

#### Compute gradients

In [73]:
loss.backward(retain_graph=True)

In [74]:
w.grad, b.grad ##Check the gradients

(tensor([[-22474.3984, -24521.5840, -15040.2031],
         [ 10846.1826,  10276.7070,   6460.2314]]),
 tensor([-267.4277,  124.1343]))

##### Pytorch accumulates gradients so we need to set them to zero:

In [78]:
w.grad.zero_
b.grad.zero_

<function Tensor.zero_>

### Gradient Descent

1)Generate Predictions\
2)Calculate loss\
3)Update weights/Bias\
4)ClearOut Gradients

In [79]:
preds = model(inputs)

In [80]:
loss = mse(preds, targets)

In [84]:
with torch.no_grad():
    w -= w.grad *1e-5
    b -= b.grad *1e-5
    w.grad.zero_()
    b.grad.zero_()

In [86]:
for i in range(20):
    preds = model(inputs)
    loss = mse(preds, targets)
    print(f'Epoch :{i}, loss:{loss.item()}')
    loss.backwards(reta)
    with torch.no_grad():
        w -= w.grad *1e-5
        b -= b.grad *1e-5
        w.grad.zero_()
        b.grad.zero_()




Epoch :0, loss:30957.693359375


AttributeError: 'Tensor' object has no attribute 'backwards'